[package]
name = "zen-proto"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "27"
glam = { version = "0.30", features = ["bytemuck"] }
bytemuck = { version = "1.24", features = ["derive"] }

[dev-dependencies]
winit = "0.30"
pollster = "0.4"
glam = { version = "0.30", features = ["rand"] }
rand = "0.9"
image = "0.25"
gltf = { version = "1", features = ["KHR_texture_transform"] }
