[workspace]
resolver = "3"
members = [
    "crates/zen-frame-graph",
    "crates/zen-renderer",
    "apps/zen-demo",
]
default-members = ["crates/zen-frame-graph", "crates/zen-renderer"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
wgpu = "30.0.1"
glam = { version = "0.30", features = ["bytemuck"] }
bytemuck = { version = "1.24", features = ["derive"] }
winit = "0.30"
pollster = "0.4"
rand = "0.9"
image = "0.25"
gltf = { version = "1", features = ["KHR_texture_transform"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
