[package]
name = "zen-render-mesh"
version = "0.1.0"
edition.workspace = true
publish = false
description = "GPU-driven Mesh domain renderer for zen-frame-graph"
readme = "README.md"

[dependencies]
zen-frame-graph = { path = "../zen-frame-graph" }
wgpu.workspace = true
glam.workspace = true
bytemuck.workspace = true
meshopt = "0.6.2"
thiserror.workspace = true

[dev-dependencies]
naga = { version = "30.0.1", features = ["wgsl-in", "spv-out"] }
pollster.workspace = true
wgpu = { workspace = true, features = ["noop"] }
